version: '3.3'
services:
  app:
    build:
      args:
        - NODE_RELEASE=${NODE_RELEASE:-12.13.0}
      context: .
    environment:
      - NODE_ENV=development
  e2e:
    build:
      context: .
      dockerfile: e2e/Dockerfile
    environment:
      - CYPRESS_BASE_URL=http://app
    links:
      - app
