---
services:
  - type: web
    plan: free
    name: starter-kit
    region: frankfurt
    env: node
    buildCommand: npm ci --include dev; npm run build; npm prune --omit dev
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: psql
          property: connectionString
      - key: LOG_LEVEL
        value: info
      - key: NODE_ENV
        value: production

databases:
  - name: psql
    region: frankfurt
    databaseName: cyf
    plan: free
