---
name: "Rotate free database on Render"

on:
  schedule:
    - cron: "0 2 * * SUN"
  workflow_dispatch:

jobs:
  rotate:
    environment: "render"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"
      - uses: "actions/setup-node@v6"
        with:
          node-version: "24"
      - run: "node ./bin/rotateDatabase.js"
        env:
          API_TOKEN: "${{ secrets.RENDER_API_TOKEN }}"
